# Generated by Django 6.0.5 on 2026-05-25 15:50

import django.db.models.deletion
import turismo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('usuario', 'usuario')], default='usuario', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
            managers=[
                ('objects', turismo.models.UserProfileManager()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Nature', 'Naturaleza'), ('Religious', 'Religioso'), ('Adventure', 'Aventura'), ('Culture', 'Cultura'), ('Beach', 'Playa')], max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('rating', models.FloatField(default=4.5)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='turismo.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=80)),
                ('max_spots', models.PositiveIntegerField()),
                ('schedule', models.CharField(max_length=180)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('rating', models.FloatField(default=4.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='turismo.place')),
            ],
        ),
    ]
